CREATE TABLE User (
    address VARCHAR(255) PRIMARY KEY,
    total_points INT NOT NULL DEFAULT 0,
    intimacy INT NOT NULL DEFAULT 0,
    likedStories JSON,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX (total_points),
    INDEX (created_at)
);